services:

  db:
    image: mysql:8.0
    container_name: auth_api_demo_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # mật khẩu root (dùng nội bộ)
      MYSQL_DATABASE: ${MYSQL_DATABASE}             # tên database → DB_NAME
      MYSQL_USER: ${MYSQL_USER}                     # user → DB_USER
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}             # mật khẩu → DB_PASSWORD
    ports:
      - "3307:3306"                                 # local:container
    volumes:
      - mysql_data:/var/lib/mysql                                    # lưu data DB
      - ./database/users.sql:/docker-entrypoint-initdb.d/users.sql  # chạy SQL khi init

  backend:
    build:
      context: .
    container_name: auth_api_demo
    volumes:
      - .:/app                            # sync code local ↔ container (hot-reload)
    depends_on:
      - db                                # đợi db khởi động trước
      - redis                             # đợi redis khởi động trước
    env_file:
      - .env                              # đọc toàn bộ biến từ file .env
    environment:
      DB_HOST: db                         # override: hostname nội bộ Docker (luôn là "db")

  redis:
    image: redis:7-alpine
    container_name: auth_api_demo_redis
    restart: always
    ports:
      - "6379:6379"                       

  nginx: 
    image: nginx:alpine
    container_name: auth_api_demo_nginx
    ports: 
      - "80:80"
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
volumes:
  mysql_data:                             